"""Structured error codes for consistent error responses across all layers."""

from enum import Enum


class ErrorCode(str, Enum):
    ENTITY_NOT_FOUND = "ENTITY_NOT_FOUND"
    DUPLICATE_ENTITY = "DUPLICATE_ENTITY"
    INVALID_STATE_TRANSITION = "INVALID_STATE_TRANSITION"

    VALIDATION_ERROR = "VALIDATION_ERROR"
    FILE_VALIDATION_ERROR = "FILE_VALIDATION_ERROR"
    JSON_DEPTH_EXCEEDED = "JSON_DEPTH_EXCEEDED"
    PAYLOAD_TOO_LARGE = "PAYLOAD_TOO_LARGE"
    MIME_TYPE_INVALID = "MIME_TYPE_INVALID"

    AUTHENTICATION_REQUIRED = "AUTHENTICATION_REQUIRED"
    TOKEN_EXPIRED = "TOKEN_EXPIRED"
    TOKEN_REVOKED = "TOKEN_REVOKED"
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
    ACCOUNT_LOCKED = "ACCOUNT_LOCKED"
    MFA_REQUIRED = "MFA_REQUIRED"
    MFA_INVALID = "MFA_INVALID"
    PASSWORD_TOO_WEAK = "PASSWORD_TOO_WEAK"
    PASSWORD_REUSED = "PASSWORD_REUSED"

    PERMISSION_DENIED = "PERMISSION_DENIED"
    TENANT_ACCESS_DENIED = "TENANT_ACCESS_DENIED"
    INSUFFICIENT_ROLE = "INSUFFICIENT_ROLE"

    RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED"
    TENANT_QUOTA_EXCEEDED = "TENANT_QUOTA_EXCEEDED"

    EXTERNAL_SERVICE_ERROR = "EXTERNAL_SERVICE_ERROR"
    EXTERNAL_SERVICE_TIMEOUT = "EXTERNAL_SERVICE_TIMEOUT"
    CIRCUIT_BREAKER_OPEN = "CIRCUIT_BREAKER_OPEN"

    GDPR_ERROR = "GDPR_ERROR"
    GDPR_ERASURE_PENDING = "GDPR_ERASURE_PENDING"
    DATA_RETENTION_VIOLATION = "DATA_RETENTION_VIOLATION"

    IDEMPOTENCY_CONFLICT = "IDEMPOTENCY_CONFLICT"

    INTERNAL_ERROR = "INTERNAL_ERROR"
    DATABASE_ERROR = "DATABASE_ERROR"
    CONFIGURATION_ERROR = "CONFIGURATION_ERROR"
