#!/usr/bin/env python3
"""Create a release_signoff.json from template for a target SHA."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


def main() -> int:
    parser = argparse.ArgumentParser(description="Create release sign-off artifact")
    parser.add_argument("--sha", required=True, help="Release SHA")
    parser.add_argument("--governance-lead", required=True, help="Governance lead full name")
    parser.add_argument("--cab-chair", required=True, help="CAB chair full name")
    parser.add_argument("--uat-report-path", required=True, help="Path to UAT report artifact")
    parser.add_argument("--rollback-report-path", required=True, help="Path to rollback drill artifact")
    parser.add_argument("--approved-at-utc", required=True, help="UTC approval timestamp")
    parser.add_argument("--output", default="docs/evidence/release_signoff.json", help="Output file path")
    args = parser.parse_args()

    payload = {
        "release_sha": args.sha,
        "governance_lead": args.governance_lead,
        "governance_lead_approved": True,
        "cab_chair": args.cab_chair,
        "cab_approved": True,
        "uat_report_path": args.uat_report_path,
        "rollback_drill_path": args.rollback_report_path,
        "notes": "Generated by create_release_signoff.py",
        "approved_at_utc": args.approved_at_utc,
    }

    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(json.dumps(payload, indent=2), encoding="utf-8")
    print(f"Wrote sign-off artifact: {output_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
