#!/usr/bin/env python3
"""Generate the ADR quarterly review issue body and print it to stdout."""
import os
import sys


def main() -> None:
    total = os.environ.get("ADR_TOTAL", "?")
    accepted = os.environ.get("ADR_ACCEPTED", "?")
    proposed = os.environ.get("ADR_PROPOSED", "?")
    quarter = os.environ.get("QUARTER", "?")
    year = os.environ.get("YEAR", "?")
    lifecycle = os.environ.get("LIFECYCLE_OUTPUT", "(not available)")

    body = (
        f"## ADR Quarterly Review -- {quarter} {year}\n\n"
        "This issue is auto-generated by the ADR quarterly review workflow to ensure "
        "Architecture Decision Records are reviewed, updated, and kept current.\n\n"
        "### Current ADR Inventory\n"
        f"- Total ADRs: {total}\n"
        f"- Accepted: {accepted}\n"
        f"- Proposed (pending decision): {proposed}\n\n"
        "### Review Checklist\n"
        "- [ ] Read all ADRs in docs/adr/ and flag any that are stale or superseded\n"
        "- [ ] Identify Proposed ADRs older than 90 days and make a decision or deprecate\n"
        "- [ ] Check for architectural decisions from the past quarter not yet documented\n"
        "- [ ] Verify all ADRs reference current file paths and component names\n"
        "- [ ] Update Status and Date fields on any reviewed ADRs\n"
        "- [ ] Close this issue when all ADRs are reviewed and new ones are written\n\n"
        "### Lifecycle Check Output\n\n"
        f"{lifecycle}\n\n"
        "### ADR Guidelines\n"
        "- New ADRs: copy the template from docs/governance/decision-log-template.md\n"
        "- Naming: ADR-NNNN-short-title.md in docs/adr/\n"
        "- Status values: Proposed | Accepted | Deprecated | Superseded\n"
    )

    output_path = os.environ.get("BODY_OUTPUT_PATH", "/tmp/adr-review-body.md")
    with open(output_path, "w") as fh:
        fh.write(body)
    print(f"[OK] Issue body written to {output_path}")


if __name__ == "__main__":
    main()
