"""Canonical AuditEvent schema

Revision ID: 7ec3d5e343a1
Revises: dfee008952ec
Create Date: 2026-01-05 00:33:10.647084+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ec3d5e343a1'
down_revision: Union[str, None] = 'dfee008952ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_root_cause_analyses_reference_number', table_name='root_cause_analyses')
    op.drop_index('ix_root_cause_analyses_title', table_name='root_cause_analyses')
    op.drop_table('root_cause_analyses')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('root_cause_analyses',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('incident_id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=300), nullable=False),
    sa.Column('problem_statement', sa.TEXT(), nullable=False),
    sa.Column('root_cause', sa.TEXT(), nullable=True),
    sa.Column('corrective_actions', sa.TEXT(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=9), nullable=False),
    sa.Column('reference_number', sa.VARCHAR(length=20), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by_id', sa.INTEGER(), nullable=True),
    sa.Column('updated_by_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_root_cause_analyses_title', 'root_cause_analyses', ['title'], unique=False)
    op.create_index('ix_root_cause_analyses_reference_number', 'root_cause_analyses', ['reference_number'], unique=1)
    # ### end Alembic commands ###
