"""Add ISO 27001 ISMS tables

Revision ID: add_iso27001_isms
Revises: add_document_control_system
Create Date: 2026-01-20 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'add_iso27001_isms'
down_revision = 'add_document_control_system'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Information Assets
    op.create_table(
        'information_asset',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('asset_id', sa.String(50), nullable=False, unique=True),
        sa.Column('name', sa.String(255), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('asset_type', sa.String(50), nullable=False),
        sa.Column('classification', sa.String(50), nullable=False, default='internal'),
        sa.Column('handling_requirements', sa.Text(), nullable=True),
        sa.Column('owner_id', sa.Integer(), nullable=True),
        sa.Column('owner_name', sa.String(255), nullable=True),
        sa.Column('custodian_id', sa.Integer(), nullable=True),
        sa.Column('custodian_name', sa.String(255), nullable=True),
        sa.Column('department', sa.String(100), nullable=True),
        sa.Column('location', sa.String(255), nullable=True),
        sa.Column('physical_location', sa.String(255), nullable=True),
        sa.Column('logical_location', sa.String(255), nullable=True),
        sa.Column('criticality', sa.String(20), nullable=False, default='medium'),
        sa.Column('business_value', sa.Text(), nullable=True),
        sa.Column('confidentiality_requirement', sa.Integer(), nullable=False, default=2),
        sa.Column('integrity_requirement', sa.Integer(), nullable=False, default=2),
        sa.Column('availability_requirement', sa.Integer(), nullable=False, default=2),
        sa.Column('dependencies', postgresql.JSONB(), nullable=True),
        sa.Column('dependent_processes', postgresql.JSONB(), nullable=True),
        sa.Column('applied_controls', postgresql.JSONB(), nullable=True),
        sa.Column('status', sa.String(20), nullable=False, default='active'),
        sa.Column('last_review_date', sa.DateTime(), nullable=True),
        sa.Column('next_review_date', sa.DateTime(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False, default=True),
        sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.func.now()),
        sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.func.now()),
        sa.PrimaryKeyConstraint('id'),
        sa.Index('ix_information_asset_asset_type', 'asset_type'),
        sa.Index('ix_information_asset_classification', 'classification'),
        sa.Index('ix_information_asset_criticality', 'criticality'),
    )

    # ISO 27001 Controls (Annex A)
    op.create_table(
        'iso27001_control',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('control_id', sa.String(20), nullable=False, unique=True),
        sa.Column('control_name', sa.String(255), nullable=False),
        sa.Column('control_description', sa.Text(), nullable=False),
        sa.Column('control_purpose', sa.Text(), nullable=True),
        sa.Column('domain', sa.String(50), nullable=False),
        sa.Column('category', sa.String(100), nullable=True),
        sa.Column('attribute_types', postgresql.JSONB(), nullable=True),
        sa.Column('implementation_guidance', sa.Text(), nullable=True),
        sa.Column('other_information', sa.Text(), nullable=True),
        sa.Column('is_applicable', sa.Boolean(), nullable=False, default=True),
        sa.Column('exclusion_justification', sa.Text(), nullable=True),
        sa.Column('implementation_status', sa.String(30), nullable=False, default='not_implemented'),
        sa.Column('implementation_notes', sa.Text(), nullable=True),
        sa.Column('implementation_date', sa.DateTime(), nullable=True),
        sa.Column('implementation_evidence', postgresql.JSONB(), nullable=True),
        sa.Column('control_owner_id', sa.Integer(), nullable=True),
        sa.Column('control_owner_name', sa.String(255), nullable=True),
        sa.Column('effectiveness_rating', sa.String(20), nullable=True),
        sa.Column('last_effectiveness_review', sa.DateTime(), nullable=True),
        sa.Column('related_policies', postgresql.JSONB(), nullable=True),
        sa.Column('related_procedures', postgresql.JSONB(), nullable=True),
        sa.Column('related_assets', postgresql.JSONB(), nullable=True),
        sa.Column('related_risks', postgresql.JSONB(), nullable=True),
        sa.Column('cross_references', postgresql.JSONB(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.func.now()),
        sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.func.now()),
        sa.PrimaryKeyConstraint('id'),
        sa.Index('ix_iso27001_control_domain', 'domain'),
        sa.Index('ix_iso27001_control_implementation_status', 'implementation_status'),
    )

    # Statement of Applicability
    op.create_table(
        'statement_of_applicability',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('version', sa.String(20), nullable=False),
        sa.Column('effective_date', sa.DateTime(), nullable=True),
        sa.Column('approved_by', sa.String(255), nullable=True),
        sa.Column('approved_by_id', sa.Integer(), nullable=True),
        sa.Column('approved_date', sa.DateTime(), nullable=True),
        sa.Column('scope_description', sa.Text(), nullable=True),
        sa.Column('risk_assessment_reference', sa.String(255), nullable=True),
        sa.Column('total_controls', sa.Integer(), nullable=False, default=93),
        sa.Column('applicable_controls', sa.Integer(), nullable=False, default=0),
        sa.Column('excluded_controls', sa.Integer(), nullable=False, default=0),
        sa.Column('implemented_controls', sa.Integer(), nullable=False, default=0),
        sa.Column('partially_implemented', sa.Integer(), nullable=False, default=0),
        sa.Column('not_implemented', sa.Integer(), nullable=False, default=0),
        sa.Column('status', sa.String(20), nullable=False, default='draft'),
        sa.Column('is_current', sa.Boolean(), nullable=False, default=False),
        sa.Column('previous_version_id', sa.Integer(), nullable=True),
        sa.Column('change_summary', sa.Text(), nullable=True),
        sa.Column('document_link', sa.String(500), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.func.now()),
        sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.func.now()),
        sa.PrimaryKeyConstraint('id'),
        sa.ForeignKeyConstraint(['previous_version_id'], ['statement_of_applicability.id']),
    )

    # SoA Control Entry
    op.create_table(
        'soa_control_entry',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('soa_id', sa.Integer(), nullable=False),
        sa.Column('control_id', sa.Integer(), nullable=False),
        sa.Column('is_applicable', sa.Boolean(), nullable=False, default=True),
        sa.Column('inclusion_justification', sa.Text(), nullable=True),
        sa.Column('exclusion_justification', sa.Text(), nullable=True),
        sa.Column('implementation_status', sa.String(30), nullable=False),
        sa.Column('implementation_description', sa.Text(), nullable=True),
        sa.Column('responsible_party', sa.String(255), nullable=True),
        sa.Column('target_completion_date', sa.DateTime(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.func.now()),
        sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.func.now()),
        sa.PrimaryKeyConstraint('id'),
        sa.ForeignKeyConstraint(['soa_id'], ['statement_of_applicability.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['control_id'], ['iso27001_control.id'], ondelete='CASCADE'),
    )

    # Information Security Risk
    op.create_table(
        'information_security_risk',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('risk_id', sa.String(50), nullable=False, unique=True),
        sa.Column('title', sa.String(255), nullable=False),
        sa.Column('description', sa.Text(), nullable=False),
        sa.Column('threat_source', sa.String(100), nullable=True),
        sa.Column('threat_description', sa.Text(), nullable=True),
        sa.Column('vulnerability', sa.Text(), nullable=True),
        sa.Column('affected_assets', postgresql.JSONB(), nullable=True),
        sa.Column('asset_classification', sa.String(50), nullable=True),
        sa.Column('confidentiality_impact', sa.Integer(), nullable=False, default=2),
        sa.Column('integrity_impact', sa.Integer(), nullable=False, default=2),
        sa.Column('availability_impact', sa.Integer(), nullable=False, default=2),
        sa.Column('likelihood', sa.Integer(), nullable=False, default=3),
        sa.Column('impact', sa.Integer(), nullable=False, default=3),
        sa.Column('inherent_risk_score', sa.Integer(), nullable=False),
        sa.Column('residual_likelihood', sa.Integer(), nullable=True),
        sa.Column('residual_impact', sa.Integer(), nullable=True),
        sa.Column('residual_risk_score', sa.Integer(), nullable=True),
        sa.Column('treatment_option', sa.String(30), nullable=False, default='mitigate'),
        sa.Column('treatment_plan', sa.Text(), nullable=True),
        sa.Column('treatment_status', sa.String(30), nullable=True),
        sa.Column('applicable_controls', postgresql.JSONB(), nullable=True),
        sa.Column('risk_owner_id', sa.Integer(), nullable=True),
        sa.Column('risk_owner_name', sa.String(255), nullable=True),
        sa.Column('status', sa.String(20), nullable=False, default='identified'),
        sa.Column('last_review_date', sa.DateTime(), nullable=True),
        sa.Column('next_review_date', sa.DateTime(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.func.now()),
        sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.func.now()),
        sa.PrimaryKeyConstraint('id'),
        sa.Index('ix_info_sec_risk_status', 'status'),
        sa.Index('ix_info_sec_risk_treatment', 'treatment_option'),
    )

    # Security Incident
    op.create_table(
        'security_incident',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('incident_id', sa.String(50), nullable=False, unique=True),
        sa.Column('title', sa.String(255), nullable=False),
        sa.Column('description', sa.Text(), nullable=False),
        sa.Column('incident_type', sa.String(50), nullable=False),
        sa.Column('severity', sa.String(20), nullable=False, default='medium'),
        sa.Column('status', sa.String(30), nullable=False, default='open'),
        sa.Column('detected_date', sa.DateTime(), nullable=False),
        sa.Column('occurred_date', sa.DateTime(), nullable=True),
        sa.Column('reported_date', sa.DateTime(), nullable=True),
        sa.Column('contained_date', sa.DateTime(), nullable=True),
        sa.Column('resolved_date', sa.DateTime(), nullable=True),
        sa.Column('cia_impact', postgresql.JSONB(), nullable=True),
        sa.Column('affected_assets', postgresql.JSONB(), nullable=True),
        sa.Column('affected_systems', postgresql.JSONB(), nullable=True),
        sa.Column('data_compromised', sa.Boolean(), nullable=False, default=False),
        sa.Column('data_types_affected', postgresql.JSONB(), nullable=True),
        sa.Column('reported_by_id', sa.Integer(), nullable=True),
        sa.Column('reported_by_name', sa.String(255), nullable=True),
        sa.Column('assigned_to_id', sa.Integer(), nullable=True),
        sa.Column('assigned_to_name', sa.String(255), nullable=True),
        sa.Column('root_cause', sa.Text(), nullable=True),
        sa.Column('containment_actions', sa.Text(), nullable=True),
        sa.Column('eradication_actions', sa.Text(), nullable=True),
        sa.Column('recovery_actions', sa.Text(), nullable=True),
        sa.Column('lessons_learned', sa.Text(), nullable=True),
        sa.Column('preventive_actions', sa.Text(), nullable=True),
        sa.Column('notification_required', sa.Boolean(), nullable=False, default=False),
        sa.Column('notification_authority', sa.String(255), nullable=True),
        sa.Column('notification_date', sa.DateTime(), nullable=True),
        sa.Column('related_risks', postgresql.JSONB(), nullable=True),
        sa.Column('related_controls', postgresql.JSONB(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.func.now()),
        sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.func.now()),
        sa.PrimaryKeyConstraint('id'),
        sa.Index('ix_security_incident_type', 'incident_type'),
        sa.Index('ix_security_incident_severity', 'severity'),
        sa.Index('ix_security_incident_status', 'status'),
    )

    # Access Control Record
    op.create_table(
        'access_control_record',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('user_name', sa.String(255), nullable=False),
        sa.Column('user_email', sa.String(255), nullable=True),
        sa.Column('user_department', sa.String(100), nullable=True),
        sa.Column('access_type', sa.String(50), nullable=False),
        sa.Column('resource_type', sa.String(50), nullable=False),
        sa.Column('resource_name', sa.String(255), nullable=False),
        sa.Column('access_level', sa.String(50), nullable=False),
        sa.Column('justification', sa.Text(), nullable=True),
        sa.Column('approved_by', sa.String(255), nullable=True),
        sa.Column('approved_by_id', sa.Integer(), nullable=True),
        sa.Column('approved_date', sa.DateTime(), nullable=True),
        sa.Column('granted_date', sa.DateTime(), nullable=True),
        sa.Column('expiry_date', sa.DateTime(), nullable=True),
        sa.Column('last_review_date', sa.DateTime(), nullable=True),
        sa.Column('next_review_date', sa.DateTime(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False, default=True),
        sa.Column('revoked_date', sa.DateTime(), nullable=True),
        sa.Column('revoked_by', sa.String(255), nullable=True),
        sa.Column('revocation_reason', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.func.now()),
        sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.func.now()),
        sa.PrimaryKeyConstraint('id'),
        sa.Index('ix_access_control_user', 'user_id'),
        sa.Index('ix_access_control_resource', 'resource_name'),
    )

    # Business Continuity Plan
    op.create_table(
        'business_continuity_plan',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('plan_id', sa.String(50), nullable=False, unique=True),
        sa.Column('plan_name', sa.String(255), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('plan_type', sa.String(50), nullable=False),
        sa.Column('scope', sa.Text(), nullable=True),
        sa.Column('critical_processes', postgresql.JSONB(), nullable=True),
        sa.Column('recovery_time_objective', sa.String(50), nullable=True),
        sa.Column('recovery_point_objective', sa.String(50), nullable=True),
        sa.Column('maximum_tolerable_downtime', sa.String(50), nullable=True),
        sa.Column('key_personnel', postgresql.JSONB(), nullable=True),
        sa.Column('contact_information', postgresql.JSONB(), nullable=True),
        sa.Column('recovery_procedures', sa.Text(), nullable=True),
        sa.Column('communication_plan', sa.Text(), nullable=True),
        sa.Column('related_assets', postgresql.JSONB(), nullable=True),
        sa.Column('dependencies', postgresql.JSONB(), nullable=True),
        sa.Column('alternate_site_details', sa.Text(), nullable=True),
        sa.Column('status', sa.String(20), nullable=False, default='draft'),
        sa.Column('version', sa.String(20), nullable=True),
        sa.Column('approved_by', sa.String(255), nullable=True),
        sa.Column('approved_date', sa.DateTime(), nullable=True),
        sa.Column('last_test_date', sa.DateTime(), nullable=True),
        sa.Column('next_test_date', sa.DateTime(), nullable=True),
        sa.Column('test_results', sa.Text(), nullable=True),
        sa.Column('last_review_date', sa.DateTime(), nullable=True),
        sa.Column('next_review_date', sa.DateTime(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False, default=True),
        sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.func.now()),
        sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.func.now()),
        sa.PrimaryKeyConstraint('id'),
        sa.Index('ix_bcp_type', 'plan_type'),
        sa.Index('ix_bcp_status', 'status'),
    )

    # Supplier Security Assessment
    op.create_table(
        'supplier_security_assessment',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('supplier_name', sa.String(255), nullable=False),
        sa.Column('supplier_type', sa.String(50), nullable=False),
        sa.Column('contact_name', sa.String(255), nullable=True),
        sa.Column('contact_email', sa.String(255), nullable=True),
        sa.Column('services_provided', sa.Text(), nullable=True),
        sa.Column('data_access_level', sa.String(50), nullable=False, default='none'),
        sa.Column('data_types_accessed', postgresql.JSONB(), nullable=True),
        sa.Column('integration_type', sa.String(50), nullable=True),
        sa.Column('assessment_date', sa.DateTime(), nullable=True),
        sa.Column('assessment_type', sa.String(50), nullable=False, default='initial'),
        sa.Column('assessor_name', sa.String(255), nullable=True),
        sa.Column('overall_rating', sa.String(30), nullable=False),
        sa.Column('security_score', sa.Integer(), nullable=True),
        sa.Column('iso27001_certified', sa.Boolean(), nullable=False, default=False),
        sa.Column('iso27001_expiry', sa.DateTime(), nullable=True),
        sa.Column('soc2_certified', sa.Boolean(), nullable=False, default=False),
        sa.Column('soc2_expiry', sa.DateTime(), nullable=True),
        sa.Column('other_certifications', postgresql.JSONB(), nullable=True),
        sa.Column('findings', postgresql.JSONB(), nullable=True),
        sa.Column('findings_count', sa.Integer(), nullable=False, default=0),
        sa.Column('critical_findings', sa.Integer(), nullable=False, default=0),
        sa.Column('risk_level', sa.String(20), nullable=False, default='medium'),
        sa.Column('contract_reference', sa.String(255), nullable=True),
        sa.Column('contract_expiry', sa.DateTime(), nullable=True),
        sa.Column('sla_requirements', postgresql.JSONB(), nullable=True),
        sa.Column('security_requirements', postgresql.JSONB(), nullable=True),
        sa.Column('assessment_frequency_months', sa.Integer(), nullable=False, default=12),
        sa.Column('next_assessment_date', sa.DateTime(), nullable=True),
        sa.Column('status', sa.String(20), nullable=False, default='active'),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.func.now()),
        sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.func.now()),
        sa.PrimaryKeyConstraint('id'),
        sa.Index('ix_supplier_assessment_rating', 'overall_rating'),
        sa.Index('ix_supplier_assessment_risk', 'risk_level'),
    )


def downgrade() -> None:
    op.drop_table('supplier_security_assessment')
    op.drop_table('business_continuity_plan')
    op.drop_table('access_control_record')
    op.drop_table('security_incident')
    op.drop_table('information_security_risk')
    op.drop_table('soa_control_entry')
    op.drop_table('statement_of_applicability')
    op.drop_table('iso27001_control')
    op.drop_table('information_asset')
