"""Initial schema - all modules

Revision ID: bdb09892867a
Revises: 
Create Date: 2026-01-04 10:37:54.699238+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdb09892867a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('permissions', sa.Text(), nullable=True),
    sa.Column('is_system_role', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('standards',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('full_name', sa.String(length=500), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('effective_date', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_standards_code'), 'standards', ['code'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('job_title', sa.String(length=100), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('audit_type', sa.String(length=50), nullable=False),
    sa.Column('frequency', sa.String(length=50), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('scoring_method', sa.String(length=50), nullable=False),
    sa.Column('passing_score', sa.Float(), nullable=True),
    sa.Column('allow_offline', sa.Boolean(), nullable=False),
    sa.Column('require_gps', sa.Boolean(), nullable=False),
    sa.Column('require_signature', sa.Boolean(), nullable=False),
    sa.Column('require_approval', sa.Boolean(), nullable=False),
    sa.Column('auto_create_findings', sa.Boolean(), nullable=False),
    sa.Column('standard_ids_json', sa.JSON(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('reference_number', sa.String(length=20), nullable=False),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_templates_name'), 'audit_templates', ['name'], unique=False)
    op.create_index(op.f('ix_audit_templates_reference_number'), 'audit_templates', ['reference_number'], unique=True)
    op.create_table('clauses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('standard_id', sa.Integer(), nullable=False),
    sa.Column('clause_number', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parent_clause_id', sa.Integer(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['parent_clause_id'], ['clauses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['standard_id'], ['standards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clauses_clause_number'), 'clauses', ['clause_number'], unique=False)
    op.create_table('complaints',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('complaint_type', sa.Enum('PRODUCT', 'SERVICE', 'DELIVERY', 'COMMUNICATION', 'BILLING', 'STAFF', 'ENVIRONMENTAL', 'SAFETY', 'OTHER', name='complainttype'), nullable=False),
    sa.Column('priority', sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', name='complaintpriority'), nullable=False),
    sa.Column('status', sa.Enum('RECEIVED', 'ACKNOWLEDGED', 'UNDER_INVESTIGATION', 'PENDING_RESPONSE', 'AWAITING_CUSTOMER', 'RESOLVED', 'CLOSED', 'ESCALATED', name='complaintstatus'), nullable=False),
    sa.Column('received_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('acknowledged_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('target_resolution_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('complainant_name', sa.String(length=200), nullable=False),
    sa.Column('complainant_email', sa.String(length=255), nullable=True),
    sa.Column('complainant_phone', sa.String(length=30), nullable=True),
    sa.Column('complainant_company', sa.String(length=200), nullable=True),
    sa.Column('complainant_address', sa.Text(), nullable=True),
    sa.Column('related_reference', sa.String(length=100), nullable=True),
    sa.Column('related_product_service', sa.String(length=200), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('investigation_notes', sa.Text(), nullable=True),
    sa.Column('root_cause', sa.Text(), nullable=True),
    sa.Column('resolution_summary', sa.Text(), nullable=True),
    sa.Column('customer_satisfied', sa.Boolean(), nullable=True),
    sa.Column('compensation_offered', sa.Text(), nullable=True),
    sa.Column('clause_ids', sa.Text(), nullable=True),
    sa.Column('linked_risk_ids', sa.Text(), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_email_id', sa.String(length=200), nullable=True),
    sa.Column('original_email_subject', sa.String(length=500), nullable=True),
    sa.Column('original_email_body', sa.Text(), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_by_id', sa.Integer(), nullable=True),
    sa.Column('closure_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('reference_number', sa.String(length=20), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['closed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_complaints_reference_number'), 'complaints', ['reference_number'], unique=True)
    op.create_index(op.f('ix_complaints_title'), 'complaints', ['title'], unique=False)
    op.create_table('incidents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('incident_type', sa.Enum('INJURY', 'NEAR_MISS', 'HAZARD', 'PROPERTY_DAMAGE', 'ENVIRONMENTAL', 'SECURITY', 'QUALITY', 'OTHER', name='incidenttype'), nullable=False),
    sa.Column('severity', sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', 'NEGLIGIBLE', name='incidentseverity'), nullable=False),
    sa.Column('status', sa.Enum('REPORTED', 'UNDER_INVESTIGATION', 'PENDING_ACTIONS', 'ACTIONS_IN_PROGRESS', 'PENDING_REVIEW', 'CLOSED', name='incidentstatus'), nullable=False),
    sa.Column('incident_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reported_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('location', sa.String(length=300), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('reporter_id', sa.Integer(), nullable=True),
    sa.Column('people_involved', sa.Text(), nullable=True),
    sa.Column('witnesses', sa.Text(), nullable=True),
    sa.Column('immediate_actions', sa.Text(), nullable=True),
    sa.Column('first_aid_given', sa.Boolean(), nullable=False),
    sa.Column('emergency_services_called', sa.Boolean(), nullable=False),
    sa.Column('investigator_id', sa.Integer(), nullable=True),
    sa.Column('investigation_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('investigation_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('root_cause', sa.Text(), nullable=True),
    sa.Column('contributing_factors', sa.Text(), nullable=True),
    sa.Column('is_riddor_reportable', sa.Boolean(), nullable=True),
    sa.Column('riddor_classification', sa.String(length=100), nullable=True),
    sa.Column('riddor_rationale', sa.Text(), nullable=True),
    sa.Column('clause_ids', sa.Text(), nullable=True),
    sa.Column('linked_risk_ids', sa.Text(), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_email_id', sa.String(length=200), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_by_id', sa.Integer(), nullable=True),
    sa.Column('closure_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('reference_number', sa.String(length=20), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['closed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['investigator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incidents_reference_number'), 'incidents', ['reference_number'], unique=True)
    op.create_index(op.f('ix_incidents_title'), 'incidents', ['title'], unique=False)
    op.create_table('policies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('document_type', sa.Enum('POLICY', 'PROCEDURE', 'WORK_INSTRUCTION', 'SOP', 'FORM', 'TEMPLATE', 'GUIDELINE', 'MANUAL', 'RECORD', 'OTHER', name='documenttype'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'UNDER_REVIEW', 'APPROVED', 'PUBLISHED', 'SUPERSEDED', 'RETIRED', name='documentstatus'), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('approver_id', sa.Integer(), nullable=True),
    sa.Column('review_frequency_months', sa.Integer(), nullable=False),
    sa.Column('next_review_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('clause_ids', sa.Text(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('restricted_to_roles', sa.Text(), nullable=True),
    sa.Column('restricted_to_departments', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('reference_number', sa.String(length=20), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['approver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policies_reference_number'), 'policies', ['reference_number'], unique=True)
    op.create_index(op.f('ix_policies_title'), 'policies', ['title'], unique=False)
    op.create_table('risks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('subcategory', sa.String(length=100), nullable=True),
    sa.Column('risk_source', sa.String(length=500), nullable=True),
    sa.Column('risk_event', sa.String(length=500), nullable=True),
    sa.Column('risk_consequence', sa.String(length=500), nullable=True),
    sa.Column('likelihood', sa.Integer(), nullable=False),
    sa.Column('impact', sa.Integer(), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('risk_level', sa.String(length=50), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('review_frequency_months', sa.Integer(), nullable=False),
    sa.Column('next_review_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('clause_ids_json', sa.JSON(), nullable=True),
    sa.Column('control_ids_json', sa.JSON(), nullable=True),
    sa.Column('linked_audit_ids_json', sa.JSON(), nullable=True),
    sa.Column('linked_incident_ids_json', sa.JSON(), nullable=True),
    sa.Column('linked_policy_ids_json', sa.JSON(), nullable=True),
    sa.Column('treatment_strategy', sa.String(length=50), nullable=False),
    sa.Column('treatment_plan', sa.Text(), nullable=True),
    sa.Column('treatment_due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('IDENTIFIED', 'ASSESSING', 'TREATING', 'MONITORING', 'CLOSED', name='riskstatus'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('reference_number', sa.String(length=20), nullable=False),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risks_reference_number'), 'risks', ['reference_number'], unique=True)
    op.create_index(op.f('ix_risks_title'), 'risks', ['title'], unique=False)
    op.create_table('road_traffic_collisions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.Enum('FATAL', 'SERIOUS_INJURY', 'MINOR_INJURY', 'DAMAGE_ONLY', 'NEAR_MISS', name='rtaseverity'), nullable=False),
    sa.Column('status', sa.Enum('REPORTED', 'UNDER_INVESTIGATION', 'PENDING_INSURANCE', 'PENDING_ACTIONS', 'CLOSED', name='rtastatus'), nullable=False),
    sa.Column('collision_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('collision_time', sa.String(length=10), nullable=True),
    sa.Column('reported_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('location', sa.String(length=500), nullable=False),
    sa.Column('road_name', sa.String(length=200), nullable=True),
    sa.Column('postcode', sa.String(length=20), nullable=True),
    sa.Column('weather_conditions', sa.String(length=100), nullable=True),
    sa.Column('road_conditions', sa.String(length=100), nullable=True),
    sa.Column('lighting_conditions', sa.String(length=100), nullable=True),
    sa.Column('company_vehicle_registration', sa.String(length=20), nullable=True),
    sa.Column('company_vehicle_make_model', sa.String(length=100), nullable=True),
    sa.Column('company_vehicle_damage', sa.Text(), nullable=True),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('driver_name', sa.String(length=200), nullable=True),
    sa.Column('driver_statement', sa.Text(), nullable=True),
    sa.Column('driver_injured', sa.Boolean(), nullable=False),
    sa.Column('driver_injury_details', sa.Text(), nullable=True),
    sa.Column('third_parties', sa.JSON(), nullable=True),
    sa.Column('witnesses', sa.Text(), nullable=True),
    sa.Column('police_attended', sa.Boolean(), nullable=False),
    sa.Column('police_reference', sa.String(length=100), nullable=True),
    sa.Column('police_station', sa.String(length=200), nullable=True),
    sa.Column('insurance_notified', sa.Boolean(), nullable=False),
    sa.Column('insurance_reference', sa.String(length=100), nullable=True),
    sa.Column('insurance_notes', sa.Text(), nullable=True),
    sa.Column('estimated_cost', sa.Integer(), nullable=True),
    sa.Column('investigator_id', sa.Integer(), nullable=True),
    sa.Column('investigation_notes', sa.Text(), nullable=True),
    sa.Column('root_cause', sa.Text(), nullable=True),
    sa.Column('fault_determination', sa.String(length=50), nullable=True),
    sa.Column('reporter_id', sa.Integer(), nullable=True),
    sa.Column('linked_risk_ids', sa.Text(), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_by_id', sa.Integer(), nullable=True),
    sa.Column('closure_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('reference_number', sa.String(length=20), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['closed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['investigator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_road_traffic_collisions_reference_number'), 'road_traffic_collisions', ['reference_number'], unique=True)
    op.create_index(op.f('ix_road_traffic_collisions_title'), 'road_traffic_collisions', ['title'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('audit_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('template_version', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('location_details', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'SCHEDULED', 'IN_PROGRESS', 'PENDING_REVIEW', 'COMPLETED', 'CANCELLED', name='auditstatus'), nullable=False),
    sa.Column('scheduled_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assigned_to_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('max_score', sa.Float(), nullable=True),
    sa.Column('score_percentage', sa.Float(), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('reference_number', sa.String(length=20), nullable=False),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['audit_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_runs_reference_number'), 'audit_runs', ['reference_number'], unique=True)
    op.create_table('audit_sections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('is_repeatable', sa.Boolean(), nullable=False),
    sa.Column('max_repeats', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['audit_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('complaint_actions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('complaint_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'IN_PROGRESS', 'COMPLETED', 'VERIFIED', 'OVERDUE', 'CANCELLED', name='actionstatus'), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_by_id', sa.Integer(), nullable=True),
    sa.Column('completion_notes', sa.Text(), nullable=True),
    sa.Column('verification_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('reference_number', sa.String(length=20), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['verified_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_complaint_actions_reference_number'), 'complaint_actions', ['reference_number'], unique=True)
    op.create_table('controls',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('clause_id', sa.Integer(), nullable=False),
    sa.Column('control_number', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('implementation_guidance', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_applicable', sa.Boolean(), nullable=False),
    sa.Column('applicability_justification', sa.Text(), nullable=True),
    sa.Column('implementation_status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['clause_id'], ['clauses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_controls_control_number'), 'controls', ['control_number'], unique=False)
    op.create_table('incident_actions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'IN_PROGRESS', 'COMPLETED', 'VERIFIED', 'OVERDUE', 'CANCELLED', name='actionstatus'), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_by_id', sa.Integer(), nullable=True),
    sa.Column('completion_notes', sa.Text(), nullable=True),
    sa.Column('verification_notes', sa.Text(), nullable=True),
    sa.Column('effectiveness_review_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('effectiveness_notes', sa.Text(), nullable=True),
    sa.Column('is_effective', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('reference_number', sa.String(length=20), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['verified_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_actions_reference_number'), 'incident_actions', ['reference_number'], unique=True)
    op.create_table('policy_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('policy_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.String(length=20), nullable=False),
    sa.Column('version_notes', sa.Text(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('is_major_revision', sa.Boolean(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('file_type', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'UNDER_REVIEW', 'APPROVED', 'PUBLISHED', 'SUPERSEDED', 'RETIRED', name='documentstatus'), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_by_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by_id', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by_id', sa.Integer(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('effective_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expiry_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('supersedes_version_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['submitted_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['supersedes_version_id'], ['policy_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('risk_assessments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('risk_id', sa.Integer(), nullable=False),
    sa.Column('assessment_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('assessment_type', sa.String(length=50), nullable=False),
    sa.Column('inherent_likelihood', sa.Integer(), nullable=False),
    sa.Column('inherent_impact', sa.Integer(), nullable=False),
    sa.Column('inherent_score', sa.Integer(), nullable=False),
    sa.Column('inherent_level', sa.String(length=50), nullable=False),
    sa.Column('residual_likelihood', sa.Integer(), nullable=False),
    sa.Column('residual_impact', sa.Integer(), nullable=False),
    sa.Column('residual_score', sa.Integer(), nullable=False),
    sa.Column('residual_level', sa.String(length=50), nullable=False),
    sa.Column('target_likelihood', sa.Integer(), nullable=True),
    sa.Column('target_impact', sa.Integer(), nullable=True),
    sa.Column('target_score', sa.Integer(), nullable=True),
    sa.Column('target_level', sa.String(length=50), nullable=True),
    sa.Column('assessment_notes', sa.Text(), nullable=True),
    sa.Column('control_effectiveness_notes', sa.Text(), nullable=True),
    sa.Column('assessed_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['assessed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['risk_id'], ['risks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('risk_controls',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('risk_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('control_type', sa.String(length=50), nullable=False),
    sa.Column('implementation_status', sa.String(length=50), nullable=False),
    sa.Column('effectiveness', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('clause_ids_json', sa.JSON(), nullable=True),
    sa.Column('control_ids_json', sa.JSON(), nullable=True),
    sa.Column('last_tested_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_test_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('test_frequency_months', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['risk_id'], ['risks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rta_actions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rta_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'IN_PROGRESS', 'COMPLETED', 'VERIFIED', 'OVERDUE', 'CANCELLED', name='actionstatus'), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_by_id', sa.Integer(), nullable=True),
    sa.Column('completion_notes', sa.Text(), nullable=True),
    sa.Column('verification_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('reference_number', sa.String(length=20), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['rta_id'], ['road_traffic_collisions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verified_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rta_actions_reference_number'), 'rta_actions', ['reference_number'], unique=True)
    op.create_table('audit_questions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=True),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('question_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('help_text', sa.String(length=500), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('allow_na', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('max_score', sa.Float(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('options_json', sa.JSON(), nullable=True),
    sa.Column('min_value', sa.Float(), nullable=True),
    sa.Column('max_value', sa.Float(), nullable=True),
    sa.Column('decimal_places', sa.Integer(), nullable=True),
    sa.Column('min_length', sa.Integer(), nullable=True),
    sa.Column('max_length', sa.Integer(), nullable=True),
    sa.Column('evidence_requirements_json', sa.JSON(), nullable=True),
    sa.Column('conditional_logic_json', sa.JSON(), nullable=True),
    sa.Column('clause_ids_json', sa.JSON(), nullable=True),
    sa.Column('control_ids_json', sa.JSON(), nullable=True),
    sa.Column('risk_category', sa.String(length=100), nullable=True),
    sa.Column('risk_weight', sa.Float(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['audit_sections.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['template_id'], ['audit_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_findings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('finding_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'IN_PROGRESS', 'PENDING_VERIFICATION', 'CLOSED', 'DEFERRED', name='findingstatus'), nullable=False),
    sa.Column('clause_ids_json', sa.JSON(), nullable=True),
    sa.Column('control_ids_json', sa.JSON(), nullable=True),
    sa.Column('risk_ids_json', sa.JSON(), nullable=True),
    sa.Column('corrective_action_required', sa.Boolean(), nullable=False),
    sa.Column('corrective_action_due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('reference_number', sa.String(length=20), nullable=False),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['audit_questions.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['audit_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_findings_reference_number'), 'audit_findings', ['reference_number'], unique=True)
    op.create_table('audit_responses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('response_value', sa.String(length=500), nullable=True),
    sa.Column('response_text', sa.Text(), nullable=True),
    sa.Column('response_number', sa.Float(), nullable=True),
    sa.Column('response_bool', sa.Boolean(), nullable=True),
    sa.Column('response_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('response_json', sa.JSON(), nullable=True),
    sa.Column('is_na', sa.Boolean(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('max_score', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['audit_questions.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['audit_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('audit_responses')
    op.drop_index(op.f('ix_audit_findings_reference_number'), table_name='audit_findings')
    op.drop_table('audit_findings')
    op.drop_table('audit_questions')
    op.drop_index(op.f('ix_rta_actions_reference_number'), table_name='rta_actions')
    op.drop_table('rta_actions')
    op.drop_table('risk_controls')
    op.drop_table('risk_assessments')
    op.drop_table('policy_versions')
    op.drop_index(op.f('ix_incident_actions_reference_number'), table_name='incident_actions')
    op.drop_table('incident_actions')
    op.drop_index(op.f('ix_controls_control_number'), table_name='controls')
    op.drop_table('controls')
    op.drop_index(op.f('ix_complaint_actions_reference_number'), table_name='complaint_actions')
    op.drop_table('complaint_actions')
    op.drop_table('audit_sections')
    op.drop_index(op.f('ix_audit_runs_reference_number'), table_name='audit_runs')
    op.drop_table('audit_runs')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_road_traffic_collisions_title'), table_name='road_traffic_collisions')
    op.drop_index(op.f('ix_road_traffic_collisions_reference_number'), table_name='road_traffic_collisions')
    op.drop_table('road_traffic_collisions')
    op.drop_index(op.f('ix_risks_title'), table_name='risks')
    op.drop_index(op.f('ix_risks_reference_number'), table_name='risks')
    op.drop_table('risks')
    op.drop_index(op.f('ix_policies_title'), table_name='policies')
    op.drop_index(op.f('ix_policies_reference_number'), table_name='policies')
    op.drop_table('policies')
    op.drop_index(op.f('ix_incidents_title'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_reference_number'), table_name='incidents')
    op.drop_table('incidents')
    op.drop_index(op.f('ix_complaints_title'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_reference_number'), table_name='complaints')
    op.drop_table('complaints')
    op.drop_index(op.f('ix_clauses_clause_number'), table_name='clauses')
    op.drop_table('clauses')
    op.drop_index(op.f('ix_audit_templates_reference_number'), table_name='audit_templates')
    op.drop_index(op.f('ix_audit_templates_name'), table_name='audit_templates')
    op.drop_table('audit_templates')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_standards_code'), table_name='standards')
    op.drop_table('standards')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_table('roles')
    # ### end Alembic commands ###
