"""Structured error codes for consistent API error responses."""


class ErrorCode:
    # Entity errors
    ENTITY_NOT_FOUND = "ENTITY_NOT_FOUND"
    DUPLICATE_ENTITY = "DUPLICATE_ENTITY"
    INVALID_STATE_TRANSITION = "INVALID_STATE_TRANSITION"

    # Validation
    VALIDATION_ERROR = "VALIDATION_ERROR"
    FILE_VALIDATION_ERROR = "FILE_VALIDATION_ERROR"
    JSON_DEPTH_EXCEEDED = "JSON_DEPTH_EXCEEDED"
    PAYLOAD_TOO_LARGE = "PAYLOAD_TOO_LARGE"
    MIME_TYPE_INVALID = "MIME_TYPE_INVALID"

    # Auth
    AUTHENTICATION_REQUIRED = "AUTHENTICATION_REQUIRED"
    TOKEN_EXPIRED = "TOKEN_EXPIRED"
    TOKEN_REVOKED = "TOKEN_REVOKED"
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
    ACCOUNT_LOCKED = "ACCOUNT_LOCKED"
    MFA_REQUIRED = "MFA_REQUIRED"
    MFA_INVALID = "MFA_INVALID"
    PASSWORD_TOO_WEAK = "PASSWORD_TOO_WEAK"
    PASSWORD_REUSED = "PASSWORD_REUSED"

    # Authorization
    PERMISSION_DENIED = "PERMISSION_DENIED"
    TENANT_ACCESS_DENIED = "TENANT_ACCESS_DENIED"
    INSUFFICIENT_ROLE = "INSUFFICIENT_ROLE"

    # Rate limiting
    RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED"
    TENANT_QUOTA_EXCEEDED = "TENANT_QUOTA_EXCEEDED"

    # External services
    EXTERNAL_SERVICE_ERROR = "EXTERNAL_SERVICE_ERROR"
    EXTERNAL_SERVICE_TIMEOUT = "EXTERNAL_SERVICE_TIMEOUT"
    CIRCUIT_BREAKER_OPEN = "CIRCUIT_BREAKER_OPEN"

    # GDPR / compliance
    GDPR_ERROR = "GDPR_ERROR"
    GDPR_ERASURE_PENDING = "GDPR_ERASURE_PENDING"
    DATA_RETENTION_VIOLATION = "DATA_RETENTION_VIOLATION"

    # Idempotency
    IDEMPOTENCY_CONFLICT = "IDEMPOTENCY_CONFLICT"

    # Internal
    INTERNAL_ERROR = "INTERNAL_ERROR"
    DATABASE_ERROR = "DATABASE_ERROR"
    CONFIGURATION_ERROR = "CONFIGURATION_ERROR"
