"""Structured error codes for consistent API error responses."""


class ErrorCode:
    ENTITY_NOT_FOUND = "ENTITY_NOT_FOUND"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    PERMISSION_DENIED = "PERMISSION_DENIED"
    TENANT_ACCESS_DENIED = "TENANT_ACCESS_DENIED"
    DUPLICATE_ENTITY = "DUPLICATE_ENTITY"
    INVALID_STATE_TRANSITION = "INVALID_STATE_TRANSITION"
    AUTHENTICATION_REQUIRED = "AUTHENTICATION_REQUIRED"
    TOKEN_EXPIRED = "TOKEN_EXPIRED"
    TOKEN_REVOKED = "TOKEN_REVOKED"
    RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED"
    FILE_VALIDATION_ERROR = "FILE_VALIDATION_ERROR"
    INTERNAL_ERROR = "INTERNAL_ERROR"
