"""Evidence Asset API schemas.

Provides Pydantic schemas for evidence asset CRUD operations with
validation for asset types, visibility, and customer pack rules.
"""

from datetime import datetime
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field, field_validator

from src.domain.models.evidence_asset import (
    EvidenceAssetType,
    EvidenceRetentionPolicy,
    EvidenceSourceModule,
    EvidenceVisibility,
)


class EvidenceAssetBase(BaseModel):
    """Base schema for evidence assets."""

    asset_type: str = Field(
        default="other",
        description="Type of evidence asset (photo, video, pdf, map_pin, etc.)",
    )
    source_module: str = Field(
        ...,
        description="Source module (near_miss, road_traffic_collision, complaint, incident, investigation)",
    )
    source_id: int = Field(..., description="ID of the source record")
    title: Optional[str] = Field(None, max_length=300, description="Asset title")
    description: Optional[str] = Field(None, description="Asset description")
    captured_at: Optional[datetime] = Field(None, description="When the evidence was captured")
    captured_by_role: Optional[str] = Field(
        None,
        max_length=100,
        description="Role of person who captured (driver, technician, etc.)",
    )
    latitude: Optional[float] = Field(None, ge=-90, le=90, description="GPS latitude")
    longitude: Optional[float] = Field(None, ge=-180, le=180, description="GPS longitude")
    location_description: Optional[str] = Field(None, max_length=500, description="Location description")
    render_hint: Optional[str] = Field(None, max_length=50, description="Render hint (thumbnail, embed, link, gallery)")
    visibility: str = Field(
        default="internal_customer",
        description="Visibility for customer packs (internal_only, internal_customer, external_allowed, public)",
    )
    contains_pii: bool = Field(default=False, description="Whether asset contains PII (faces, plates, etc.)")
    redaction_required: bool = Field(
        default=False,
        description="Whether asset needs redaction before external sharing",
    )
    retention_policy: str = Field(default="standard", description="Retention policy")
    metadata_json: Optional[Dict[str, Any]] = Field(None, description="Extended metadata")

    @field_validator("asset_type")
    @classmethod
    def validate_asset_type(cls, v: str) -> str:
        """Validate asset type is valid."""
        valid_types = {e.value for e in EvidenceAssetType}
        if v not in valid_types:
            raise ValueError(f"Invalid asset type: {v}. Must be one of {valid_types}")
        return v

    @field_validator("source_module")
    @classmethod
    def validate_source_module(cls, v: str) -> str:
        """Validate source module is valid."""
        valid_modules = {e.value for e in EvidenceSourceModule}
        if v not in valid_modules:
            raise ValueError(f"Invalid source module: {v}. Must be one of {valid_modules}")
        return v

    @field_validator("visibility")
    @classmethod
    def validate_visibility(cls, v: str) -> str:
        """Validate visibility is valid."""
        valid_visibility = {e.value for e in EvidenceVisibility}
        if v not in valid_visibility:
            raise ValueError(f"Invalid visibility: {v}. Must be one of {valid_visibility}")
        return v

    @field_validator("retention_policy")
    @classmethod
    def validate_retention_policy(cls, v: str) -> str:
        """Validate retention policy is valid."""
        valid_policies = {e.value for e in EvidenceRetentionPolicy}
        if v not in valid_policies:
            raise ValueError(f"Invalid retention policy: {v}. Must be one of {valid_policies}")
        return v


class EvidenceAssetCreate(BaseModel):
    """Schema for creating an evidence asset (via file upload).

    Note: storage_key and content_type are generated by the upload handler.
    """

    asset_type: str = Field(default="photo", description="Type of evidence asset")
    source_module: str = Field(..., description="Source module")
    source_id: int = Field(..., description="ID of the source record")
    title: Optional[str] = Field(None, max_length=300)
    description: Optional[str] = Field(None)
    captured_at: Optional[datetime] = Field(None)
    captured_by_role: Optional[str] = Field(None, max_length=100)
    latitude: Optional[float] = Field(None, ge=-90, le=90)
    longitude: Optional[float] = Field(None, ge=-180, le=180)
    location_description: Optional[str] = Field(None, max_length=500)
    visibility: str = Field(default="internal_customer")
    contains_pii: bool = Field(default=False)
    redaction_required: bool = Field(default=False)
    metadata_json: Optional[Dict[str, Any]] = Field(None)

    @field_validator("asset_type")
    @classmethod
    def validate_asset_type(cls, v: str) -> str:
        valid_types = {e.value for e in EvidenceAssetType}
        if v not in valid_types:
            raise ValueError(f"Invalid asset type: {v}. Must be one of {valid_types}")
        return v

    @field_validator("source_module")
    @classmethod
    def validate_source_module(cls, v: str) -> str:
        valid_modules = {e.value for e in EvidenceSourceModule}
        if v not in valid_modules:
            raise ValueError(f"Invalid source module: {v}. Must be one of {valid_modules}")
        return v

    @field_validator("visibility")
    @classmethod
    def validate_visibility(cls, v: str) -> str:
        valid_visibility = {e.value for e in EvidenceVisibility}
        if v not in valid_visibility:
            raise ValueError(f"Invalid visibility: {v}. Must be one of {valid_visibility}")
        return v


class EvidenceAssetUpdate(BaseModel):
    """Schema for updating an evidence asset."""

    title: Optional[str] = Field(None, max_length=300)
    description: Optional[str] = Field(None)
    captured_at: Optional[datetime] = Field(None)
    captured_by_role: Optional[str] = Field(None, max_length=100)
    latitude: Optional[float] = Field(None, ge=-90, le=90)
    longitude: Optional[float] = Field(None, ge=-180, le=180)
    location_description: Optional[str] = Field(None, max_length=500)
    render_hint: Optional[str] = Field(None, max_length=50)
    visibility: Optional[str] = Field(None)
    contains_pii: Optional[bool] = Field(None)
    redaction_required: Optional[bool] = Field(None)
    retention_policy: Optional[str] = Field(None)
    linked_investigation_id: Optional[int] = Field(None)
    metadata_json: Optional[Dict[str, Any]] = Field(None)

    @field_validator("visibility")
    @classmethod
    def validate_visibility(cls, v: Optional[str]) -> Optional[str]:
        if v is None:
            return v
        valid_visibility = {e.value for e in EvidenceVisibility}
        if v not in valid_visibility:
            raise ValueError(f"Invalid visibility: {v}. Must be one of {valid_visibility}")
        return v

    @field_validator("retention_policy")
    @classmethod
    def validate_retention_policy(cls, v: Optional[str]) -> Optional[str]:
        if v is None:
            return v
        valid_policies = {e.value for e in EvidenceRetentionPolicy}
        if v not in valid_policies:
            raise ValueError(f"Invalid retention policy: {v}. Must be one of {valid_policies}")
        return v


class EvidenceAssetResponse(BaseModel):
    """Schema for evidence asset response."""

    id: int
    storage_key: str
    original_filename: Optional[str] = None
    content_type: str
    file_size_bytes: Optional[int] = None
    checksum_sha256: Optional[str] = None
    asset_type: str
    source_module: str
    source_id: int
    linked_investigation_id: Optional[int] = None
    title: Optional[str] = None
    description: Optional[str] = None
    captured_at: Optional[datetime] = None
    captured_by_role: Optional[str] = None
    latitude: Optional[float] = None
    longitude: Optional[float] = None
    location_description: Optional[str] = None
    render_hint: Optional[str] = None
    thumbnail_storage_key: Optional[str] = None
    metadata_json: Optional[Dict[str, Any]] = None
    visibility: str
    contains_pii: bool
    redaction_required: bool
    retention_policy: str
    retention_expires_at: Optional[datetime] = None
    created_at: datetime
    updated_at: datetime
    created_by_id: Optional[int] = None
    updated_by_id: Optional[int] = None

    class Config:
        from_attributes = True


class EvidenceAssetListResponse(BaseModel):
    """Schema for paginated evidence asset list."""

    items: List[EvidenceAssetResponse]
    total: int
    page: int
    page_size: int
    pages: int


class EvidenceAssetUploadResponse(BaseModel):
    """Schema for file upload response."""

    id: int
    storage_key: str
    original_filename: str
    content_type: str
    file_size_bytes: int
    upload_url: Optional[str] = None  # Presigned URL for direct upload if applicable
    message: str = "File uploaded successfully"


class BulkEvidenceAssetCreate(BaseModel):
    """Schema for bulk evidence asset creation (e.g., migrating NearMiss attachments)."""

    assets: List[EvidenceAssetCreate] = Field(..., min_length=1, max_length=50)


class BulkEvidenceAssetResponse(BaseModel):
    """Schema for bulk creation response."""

    created: List[EvidenceAssetResponse]
    failed: List[Dict[str, Any]]  # List of failed items with error details
    total_created: int
    total_failed: int
