#!/usr/bin/env python3
"""Ratchet Pydantic write-schema ``extra="forbid"`` coverage (board B-10 / w4-extra-forbid).

Why this exists
---------------
Pydantic defaults to ``extra="ignore"``, so a client that posts an unrecognised
body field gets 2xx and no indication the value was dropped (PX-168). Only
``model_config = ConfigDict(extra="forbid")`` makes FastAPI return 422, and that
is what OpenAPI encodes as ``additionalProperties: false``.

Contract Guard 2 (``tests/contract/test_write_contract_guards.py``) already
blocks *unrecorded* new open schemas via ``KNOWN_LAX_WRITE_SCHEMAS``. That
allowlist does not pin counts: removing ``extra="forbid"`` from a schema that
remains listed (or swapping forbid membership while counts stay flat) would
not fail the allowlist gate. This script closes that hole with a numeric
inventory lock measured from ``origin/main``.

What it does
------------
* Discovers every POST/PUT/PATCH JSON ``$ref`` request body in ``app.openapi()``.
* Counts schemas with ``additionalProperties: false`` (forbid) vs without (open).
* Fails when the forbid count **decreases**, when the open count **increases**
  above the committed baseline, or when a baseline forbid schema loses forbid.
* Warns (exit 0) when the backlog shrinks — refresh the baseline so the ratchet
  tightens. Same posture as ``validate_alembic_drift_ratchet.py``.

What it deliberately does not do
--------------------------------
* Convert the 294 open schemas. That is follow-up work; this PR only locks the
  inventory so the hole cannot grow.
* Edit ``KNOWN_LAX_WRITE_SCHEMAS``. That allowlist is a separate remediation
  roadmap; do not touch it from this gate.

Refreshing the baseline
-----------------------
    python3 scripts/validate_write_schema_extra_forbid_ratchet.py --write-baseline
    python3 scripts/validate_write_schema_extra_forbid_ratchet.py --markdown \\
      docs/governance/write_schema_extra_forbid_inventory.md
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path
from typing import Any, Optional

REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_BASELINE = REPO_ROOT / "docs" / "governance" / "write_schema_extra_forbid_baseline.json"
DEFAULT_MARKDOWN = REPO_ROOT / "docs" / "governance" / "write_schema_extra_forbid_inventory.md"


class RatchetFailure(Exception):
    """A write-schema condition that must block the merge."""


def _ensure_repo_importable() -> None:
    path = str(REPO_ROOT)
    if path not in sys.path:
        sys.path.insert(0, path)


def _seed_minimal_env() -> None:
    """Allow ``app.openapi()`` import in CI without a live database."""
    os.environ.setdefault("TESTING", "1")
    os.environ.setdefault("SECRET_KEY", "write-schema-ratchet-not-for-production")
    os.environ.setdefault("DATABASE_URL", "sqlite+aiosqlite:///:memory:")
    os.environ.setdefault("AZURE_TENANT_ID", "ci-tenant-id")
    os.environ.setdefault("AZURE_CLIENT_ID", "ci-client-id")
    os.environ.setdefault("AZURE_CLIENT_SECRET", "ci-client-secret")
    os.environ.setdefault("DEFAULT_TENANT_ID", "1")


def inventory_write_schemas() -> dict[str, Any]:
    """Enumerate OpenAPI write request models and classify forbid vs open."""
    _ensure_repo_importable()
    _seed_minimal_env()
    from tests.contract._write_contract_support import forbids_extra_fields, write_operations

    ops = write_operations()
    models = sorted({op.request_model for op in ops})
    forbid = sorted(m for m in models if forbids_extra_fields(m))
    open_schemas = sorted(m for m in models if not forbids_extra_fields(m))
    operations_by_schema: dict[str, list[str]] = {m: [] for m in models}
    for op in ops:
        operations_by_schema[op.request_model].append(op.label)
    for name in operations_by_schema:
        operations_by_schema[name] = sorted(set(operations_by_schema[name]))

    return {
        "total_write_schemas": len(models),
        "forbid_count": len(forbid),
        "open_count": len(open_schemas),
        "forbid_schemas": forbid,
        "open_schemas": open_schemas,
        "operations_by_schema": operations_by_schema,
        "write_operation_count": len(ops),
    }


def build_baseline(current: dict[str, Any]) -> dict[str, Any]:
    """Committed ceiling for open schemas / floor for forbid schemas."""
    return {
        "_comment": (
            "Inventory lock for Pydantic write-schema extra='forbid' coverage "
            "(board B-10 / w4-extra-forbid). Generated by "
            "scripts/validate_write_schema_extra_forbid_ratchet.py --write-baseline. "
            "min_forbid_count is a floor (fails when it falls); max_open_count is a "
            "ceiling (fails when it rises). forbid_schemas must remain forbid."
        ),
        "total_write_schemas": current["total_write_schemas"],
        "min_forbid_count": current["forbid_count"],
        "max_open_count": current["open_count"],
        "forbid_schemas": list(current["forbid_schemas"]),
        "write_operation_count": current["write_operation_count"],
    }


def check_ratchet(current: dict[str, Any], baseline: dict[str, Any]) -> tuple[list[str], list[str]]:
    """Compare live inventory against the committed baseline.

    Returns ``(failures, warnings)``. Failures block merge; warnings mean the
    backlog improved and the baseline should be refreshed.
    """
    failures: list[str] = []
    warnings: list[str] = []

    min_forbid = int(baseline["min_forbid_count"])
    max_open = int(baseline["max_open_count"])
    forbid_now = int(current["forbid_count"])
    open_now = int(current["open_count"])
    baseline_forbid = set(baseline.get("forbid_schemas") or [])
    current_forbid = set(current.get("forbid_schemas") or [])

    lost = sorted(baseline_forbid - current_forbid)
    if lost:
        failures.append(
            f"{len(lost)} baseline forbid schema(s) no longer reject unknown fields: "
            f"{', '.join(lost)}. Restoring extra='forbid' (or refreshing the baseline "
            "in a PR that explains the regression) is required."
        )

    if forbid_now < min_forbid:
        failures.append(
            f"forbid count fell from baseline floor {min_forbid} to {forbid_now}. "
            "Do not remove extra='forbid' from write schemas without replacing coverage."
        )

    if open_now > max_open:
        failures.append(
            f"open (non-forbid) write schema count rose from baseline ceiling {max_open} "
            f"to {open_now}. New write request bodies must declare "
            "model_config = ConfigDict(extra='forbid'), or the baseline must be "
            "explicitly raised with review."
        )

    if forbid_now > min_forbid:
        warnings.append(
            f"forbid count rose from {min_forbid} to {forbid_now} — baseline is stale; "
            "refresh with --write-baseline so the ratchet tightens."
        )
    if open_now < max_open:
        warnings.append(
            f"open count fell from {max_open} to {open_now} — baseline is stale; "
            "refresh with --write-baseline so the ratchet tightens."
        )

    gained = sorted(current_forbid - baseline_forbid)
    if gained and forbid_now >= min_forbid:
        warnings.append(
            f"{len(gained)} schema(s) newly forbid unknown fields: {', '.join(gained)}. "
            "Include them in the next baseline refresh."
        )

    return failures, warnings


def render_markdown(current: dict[str, Any], baseline: Optional[dict[str, Any]] = None) -> str:
    """Human-readable inventory for governance docs."""
    lines = [
        '# Write-schema `extra="forbid"` inventory (B-10 / w4-extra-forbid)',
        "",
        "Generated by `scripts/validate_write_schema_extra_forbid_ratchet.py`.",
        "Discovery is OpenAPI-driven: every POST/PUT/PATCH operation with a named",
        "JSON request body model. `additionalProperties: false` means",
        '`ConfigDict(extra="forbid")`.',
        "",
        "## Summary",
        "",
        "| Metric | Count |",
        "| --- | ---: |",
        f"| Distinct write schemas | {current['total_write_schemas']} |",
        f"| `extra=\"forbid\"` (strict) | {current['forbid_count']} |",
        f"| Open / lax (unknown fields ignored) | {current['open_count']} |",
        f"| Write operations (POST/PUT/PATCH) | {current['write_operation_count']} |",
        "",
    ]
    if baseline:
        lines += [
            "## Committed ratchet",
            "",
            f"| Floor / ceiling | Value |",
            f"| --- | ---: |",
            f"| `min_forbid_count` | {baseline['min_forbid_count']} |",
            f"| `max_open_count` | {baseline['max_open_count']} |",
            "",
            "CI fails if forbid count decreases or open count increases above these",
            "values (see `docs/governance/write_schema_extra_forbid_baseline.json`).",
            "",
        ]
    lines += [
        '## Strict schemas (`extra="forbid"`)',
        "",
    ]
    if current["forbid_schemas"]:
        for name in current["forbid_schemas"]:
            ops = ", ".join(f"`{op}`" for op in current["operations_by_schema"].get(name, []))
            lines.append(f"- `{name}` — {ops or '(no operations discovered)'}")
    else:
        lines.append("_None._")
    lines += [
        "",
        "## Open schemas (unknown fields silently ignored)",
        "",
        f"{current['open_count']} schemas. Full list is the remediation backlog;",
        "converting them is out of scope for the inventory lock PR.",
        "",
        "<details>",
        "<summary>Open schema names</summary>",
        "",
    ]
    for name in current["open_schemas"]:
        lines.append(f"- `{name}`")
    lines += ["", "</details>", ""]
    return "\n".join(lines)


def _print_report(current: dict[str, Any]) -> None:
    print("=== Write-schema extra=forbid ratchet ===")
    print(f"write operations: {current['write_operation_count']}")
    print(f"distinct write schemas: {current['total_write_schemas']}")
    print(f"extra=forbid: {current['forbid_count']}")
    print(f"open (non-forbid): {current['open_count']}")
    if current["forbid_schemas"]:
        print("forbid schemas:")
        for name in current["forbid_schemas"]:
            print(f"  {name}")


def main(argv: Optional[list[str]] = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--baseline", type=Path, default=DEFAULT_BASELINE)
    parser.add_argument(
        "--inventory-json",
        type=Path,
        default=None,
        help="Optional path to write the live inventory JSON.",
    )
    parser.add_argument(
        "--markdown",
        type=Path,
        nargs="?",
        const=DEFAULT_MARKDOWN,
        default=None,
        help="Write the Markdown inventory (default path if flag given with no value).",
    )
    parser.add_argument("--write-baseline", action="store_true", help="Rewrite the baseline from this run.")
    parser.add_argument(
        "--from-inventory",
        type=Path,
        default=None,
        help="Use a precomputed inventory JSON instead of importing the app (tests).",
    )
    args = parser.parse_args(argv)

    try:
        if args.from_inventory is not None:
            if not args.from_inventory.is_file():
                raise RatchetFailure(f"inventory not found at {args.from_inventory}")
            current = json.loads(args.from_inventory.read_text(encoding="utf-8"))
        else:
            current = inventory_write_schemas()
    except RatchetFailure as exc:
        print(f"[FAIL] {exc}", file=sys.stderr)
        return 1
    except Exception as exc:  # noqa: BLE001 - surface import/discovery failures
        print(f"[FAIL] could not inventory write schemas: {exc!r}", file=sys.stderr)
        return 1

    _print_report(current)

    if args.inventory_json is not None:
        args.inventory_json.parent.mkdir(parents=True, exist_ok=True)
        args.inventory_json.write_text(json.dumps(current, indent=2, sort_keys=True) + "\n", encoding="utf-8")
        print(f"[OK] inventory written to {args.inventory_json}")

    if args.write_baseline:
        payload = build_baseline(current)
        args.baseline.parent.mkdir(parents=True, exist_ok=True)
        args.baseline.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")
        print(f"[OK] baseline written to {args.baseline}")
        if args.markdown is not None:
            args.markdown.parent.mkdir(parents=True, exist_ok=True)
            args.markdown.write_text(render_markdown(current, payload), encoding="utf-8")
            print(f"[OK] markdown written to {args.markdown}")
        return 0

    if not args.baseline.is_file():
        print(f"[FAIL] no baseline at {args.baseline}; generate one with --write-baseline", file=sys.stderr)
        return 1

    baseline = json.loads(args.baseline.read_text(encoding="utf-8"))
    for key in ("min_forbid_count", "max_open_count", "forbid_schemas"):
        if key not in baseline:
            print(f"[FAIL] baseline missing required key {key!r}", file=sys.stderr)
            return 1

    if args.markdown is not None:
        args.markdown.parent.mkdir(parents=True, exist_ok=True)
        args.markdown.write_text(render_markdown(current, baseline), encoding="utf-8")
        print(f"[OK] markdown written to {args.markdown}")

    failures, warnings = check_ratchet(current, baseline)
    for warning in warnings:
        print(f"[WARN] {warning}")
    for failure in failures:
        print(f"[FAIL] {failure}", file=sys.stderr)

    if failures:
        print(f"[FAIL] {len(failures)} write-schema extra=forbid ratchet violation(s).", file=sys.stderr)
        return 1

    print(
        f"[OK] {current['forbid_count']} forbid / {current['open_count']} open "
        f"(floor {baseline['min_forbid_count']}, ceiling {baseline['max_open_count']}); "
        f"baseline forbid set intact."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
